
USE DBPisersa
GO

CREATE TABLE T_M41(--SERVICIO
	TM41_ID int NOT NULL,--PK
	TM41_TM2_ID varchar(50) NOT NULL,
	TM41_TM42_ID int, --FK TIPO falta
	TM41_DESCRIP varchar(300) NULL,
	TM41_ST smallint,--*
	TM41_FLG_ELIMINADO smallint,--*
	TM41_UCREA varchar(20) NULL,
	TM41_FCREA datetime NULL,
	TM41_UACTUALIZA varchar(20) NULL,
	TM41_FACTUALIZA datetime NULL,
	Primary Key(TM41_ID)
	);
	SELECT * FROM T_M41

	--CONSTRAINT FK_TR28_TM41 FOREIGN KEY (TR28_TM41_ID) REFERENCES TM41 (TM41_ID)
GO

CREATE TABLE T_M42( --TIPO
	TM42_ID int, --PK
	--TM42_TM2_ID varchar,
	TM42_DESCRIP varchar(300),
	TM42_ST smallint,
	TM42_FLG_ELIMINADO smallint,
	TM42_UCREA varchar (20),
	TM42_FCREA datetime,
	TM42_UACTUALIZA varchar (20),
	TM42_FACTUALIZA datetime,
	Primary Key(TM42_ID)
	);

	GO

	SELECT * FROM T_M42 --Tipo de Servicio(NUEVO)
	INSERT INTO T_M42 VALUES (1,'Generales',1,0,'',GETDATE(),'',GETDATE())
	INSERT INTO T_M42 VALUES (2,'Complementarios',1,0,'',GETDATE(),'',GETDATE())
	INSERT INTO T_M42 VALUES (3,'Adicionales',1,0,'',GETDATE(),'',GETDATE())
	INSERT INTO T_M42 VALUES (4,'Especiales',1,0,'',GETDATE(),'',GETDATE())
	GO


	INSERT INTO T_M41 VALUES(4,	'PIS',	'Servicio General de Limpieza',	'NULL',GETDATE(),	NULL,GETDATE(),1,1,0)
	INSERT INTO T_M41 VALUES(5,	'PIS',	'Servicio de Fumigación',	NULL,	GETDATE(),	NULL,GETDATE(),1,1,0)
	INSERT INTO T_M41 VALUES(6,	'PIS',	'Servicio de Desratización',	NULL,	GETDATE(),NULL,GETDATE(),1,1,0)
	GO
	INSERT INTO T_M41 VALUES(7,	'PIS',	'Servicio General de Limpieza',	'NULL',	GETDATE(),	NULL,GETDATE(),4,1,0)
	INSERT INTO T_M41 VALUES(8,	'PIS',	'Servicio de Fumigación',	NULL,	GETDATE(),	NULL,GETDATE(),4,1,0)
	INSERT INTO T_M41 VALUES(9,	'PIS',	'Servicio de Desratización',	NULL,	GETDATE(),NULL,GETDATE(),4,1,0)

	SELECT * FROM T_M41
	ALTER TABLE T_M41 ADD CONSTRAINT FK_TM41_TM42 FOREIGN KEY (TM41_TM42_ID) REFERENCES T_M42 (TM42_ID)
	ALTER TABLE T_R28 ADD CONSTRAINT FK_TR28_TM41 FOREIGN KEY (TR28_TM41_ID) REFERENCES TM41 (TM41_ID)
